import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import { BubbleAnimation, Navbar, Revenue } from "../components";
import { Providers } from "./providers";
import { cookieToInitialState } from "wagmi";
import { config } from "../config";
import { headers } from "next/headers";

const Poet = LocalFont({ src: "./fonts/PoetsenOne-Regular.ttf" });

export const metadata: Metadata = {
  title: "BabydogeX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en">
      <body className={Poet.className}>
        <Providers initialState={initialState}>
          <div className="overflow-hidden fixed inset-0">
            <BubbleAnimation/>
          </div>
          <main className="p-4 lg:container min-h-screen w-full lg:w-10/12 md:p-6 flex flex-col">
            <Revenue/>
            <Navbar
              items={
                [
                  { link: '/', title: 'Hybrid NFT' },
                  { link: '/ai', title: 'AI' }
                ]
            }/>
            <div className="mt-2 p-2 flex-grow flex flex-col">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
